language: node_js
node_js:
  - "10"
  - "12"
after_success:
  - curl -Lo travis_after_all.py https://raw.githubusercontent.com/contentful/travis_after_all/master/travis_after_all.py
  - python travis_after_all.py
  - codecov
  - npm run semantic-release
